# Generated by Django 4.1.5 on 2023-04-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('phone', models.TextField(max_length=10)),
                ('password', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('companyname', models.CharField(max_length=45, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('message', models.TextField(max_length=300)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('skill', models.TextField(max_length=45)),
                ('phone', models.TextField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.TextField(max_length=255)),
                ('password', models.TextField(max_length=255)),
            ],
        ),
    ]
