# Generated by Django 4.1.5 on 2023-04-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('username', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('companyname', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('password', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('message', models.TextField(max_length=300)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('username', models.TextField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('job', models.TextField(max_length=50)),
                ('skill', models.TextField(max_length=50)),
                ('hobbies', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=10)),
                ('address', models.TextField(max_length=500)),
                ('password', models.TextField(max_length=50)),
            ],
        ),
    ]
