# Generated by Django 4.1.5 on 2023-04-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
