# Generated by Django 4.1.5 on 2023-03-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.TextField(max_length=10)),
            ],
        ),
    ]
