# Generated by Django 4.1.5 on 2023-03-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0002_alter_company_email_alter_signup_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_log',
            name='address',
        ),
        migrations.RemoveField(
            model_name='admin_log',
            name='hobbies',
        ),
    ]
