# Generated by Django 4.1.5 on 2023-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0002_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_log',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
