# Generated by Django 4.1.5 on 2023-03-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0002_admin_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
    ]
