# Generated by Django 4.1.5 on 2023-04-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='catagory_name',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
