# Generated by Django 4.1.5 on 2023-04-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('message', models.TextField(max_length=300)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=50)),
                ('job_title', models.TextField(max_length=30)),
                ('company_location', models.TextField(max_length=50)),
                ('salary', models.TextField(max_length=50)),
                ('experience_required', models.TextField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('skill_required', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.TextField(max_length=10)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('last_date', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('job_description', models.TextField(max_length=50)),
            ],
        ),
    ]
