# Generated by Django 4.1.5 on 2023-04-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(max_length=30)),
                ('company_location', models.TextField(max_length=50)),
                ('salary', models.TextField(max_length=50)),
                ('experience_required', models.TextField(max_length=50)),
                ('skill_required', models.CharField(max_length=20)),
                ('post_date', models.DateField(max_length=15)),
                ('last_date', models.DateField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('job_description', models.TextField(max_length=50)),
            ],
        ),
    ]
