# Generated by Django 4.1.5 on 2023-04-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='last_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
