# Generated by Django 4.1.5 on 2023-04-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='last_date',
            field=models.DateField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='post_date',
            field=models.DateField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='skill_required',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
