# Generated by Django 4.1.5 on 2023-04-23 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0003_alter_jobpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('jobapplication_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('resume', models.FileField(upload_to='media')),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.jobpost')),
            ],
        ),
    ]
